baseurl = "https://sonix.network/"
title = "SONIX"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"
summaryLength = 70
paginate = 10

[menu]

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "IX"
    identifier = "menu.ix"
    weight     = 3

[[menu.main]]
    name       = "Documentation"
    identifier = "section.docs"
    url        = ""
    weight     = 1
    parent     = "menu.ix"
    post       = 1

[[menu.main]]
    name       = "Services"
    identifier = "section.services"
    url        = ""
    weight     = 2
    parent     = "menu.ix"
    post       = 2

[[menu.main]]
    name       = "Operations"
    identifier = "section.ops"
    url        = ""
    weight     = 3
    parent     = "menu.ix"
    post       = 1

[[menu.main]]
    name       = "Rules"
    url        = "/rules/"
    weight     = 1
    parent     = "section.docs"

[[menu.main]]
    name       = "TRex"
    url        = "/ops/trex/"
    weight     = 1
    parent     = "section.ops"

[[menu.main]]
    name       = "Grafana"
    url        = "https://metric.sonix.network"
    weight     = 1
    parent     = "section.services"

[[menu.main]]
    name       = "PeeringDB"
    url        = "https://peeringdb.com/ix/3607"
    weight     = 2
    parent     = "section.services"

[[menu.main]]
    name       = "IXP Manager"
    url        = "https://manager.sonix.network/"
    weight     = 3
    parent     = "section.services"

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


[params]
    author = "SONIX"
    mainSections = []
    defaultDescription = "Open Internet Exchange for Everybody"

    style = "blue"

    about_us = """<p>Founded by a non-profit, SONIX will live as a community driven IXP. If you have an idea where SONIX can help out we would love to hear it!</p>"""
    copyright = "Copyright (c) SONIX; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "SONIX"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"

[permalinks]
    posts = "/posts/:year/:month/:day/:filename/"

[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false

[params.see_more]
    enable = true
    icon = "fas fa-user-friends"
    title = "Do you want to learn more?"
    subtitle = "Join our Matrix channel and we would be happy to explain more!"
    link_url = "/contact/"
    link_text = "Contact us"

[params.clients]
    enable = true
    title = "Our members"
    subtitle = ""

[params.recent_posts]
    enable = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
